# Generated by Django 5.2.12 on 2026-05-27 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_off_days', models.JSONField(blank=True, default=list)),
                ('banned_days', models.JSONField(blank=True, default=list)),
                ('no_morning', models.BooleanField(default=False)),
                ('no_evening', models.BooleanField(default=False)),
                ('lunch_break', models.BooleanField(default=False)),
                ('max_credits', models.IntegerField(default=18)),
                ('min_credits', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timetables_userpreference',
            },
        ),
    ]
