# Generated by Django 5.2.12 on 2026-05-28 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('course_registration', '수강신청'), ('career', '취업진로'), ('exchange', '교환학생'), ('grant', '지원사업'), ('academic', '학업관리')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='themes_them_is_acti_884881_idx'), models.Index(fields=['category'], name='themes_them_categor_55e1ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='')),
                ('external_url', models.URLField(blank=True, default='', max_length=500)),
                ('item_type', models.CharField(choices=[('guide', '가이드'), ('checklist', '체크리스트'), ('link', '외부 링크')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='themes.theme')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['theme', 'order'], name='themes_them_theme_i_4cc923_idx')],
            },
        ),
    ]
