# Generated by Django 5.2.12 on 2026-05-26 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=10, verbose_name='역할')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/%Y/%m/', verbose_name='업로드 파일')),
                ('file_type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('document', 'document')], max_length=20, verbose_name='파일 종류')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage', verbose_name='메시지')),
            ],
            options={
                'verbose_name': '채팅 첨부파일',
                'verbose_name_plural': '채팅 첨부파일',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='채팅방 제목')),
                ('category', models.CharField(choices=[('수강·졸업', '수강·졸업'), ('공지', '공지'), ('장학·등록금', '장학·등록금'), ('공모전', '공모전'), ('취업·진로', '취업·진로'), ('일반질문', '일반질문'), ('기타', '기타')], default='기타', max_length=20, verbose_name='카테고리')),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=200, verbose_name='마지막 메시지 미리보기')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatrooms', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='채팅방'),
        ),
    ]
