# Generated by Django 5.2.12 on 2026-05-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='referenced_items',
            field=models.JSONField(blank=True, default=list, help_text='AI가 search_notices / search_information tool로 가져온 카드 데이터 snapshot — [{type, title, url}] 형식. type ∈ {notice, information}. user 메시지는 빈 배열.', verbose_name='참조 항목 (공지/정보 title+url snapshot)'),
        ),
    ]
