# Generated by Django 5.2.12 on 2026-04-04 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='이름')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='전공')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='학년')),
                ('semester', models.IntegerField(blank=True, null=True, verbose_name='학기')),
                ('graduation_year', models.IntegerField(blank=True, null=True, verbose_name='졸업 희망 연도')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='이메일 인증 여부')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='알림 수신 여부')),
                ('kakao_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='카카오 ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
            },
        ),
        migrations.CreateModel(
            name='CourseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='과목명')),
                ('course_code', models.CharField(max_length=30, verbose_name='과목번호')),
                ('year', models.IntegerField(verbose_name='수강 연도')),
                ('semester', models.IntegerField(verbose_name='수강 학기')),
                ('grade_received', models.CharField(blank=True, max_length=10, verbose_name='취득 성적')),
                ('category', models.CharField(max_length=20, verbose_name='이수구분')),
                ('credits', models.IntegerField(verbose_name='학점 수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '수강이력',
                'verbose_name_plural': '수강이력',
            },
        ),
        migrations.CreateModel(
            name='CurrentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='과목명')),
                ('course_code', models.CharField(max_length=30, verbose_name='과목번호')),
                ('day_of_week', models.CharField(max_length=5, verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('professor', models.CharField(blank=True, max_length=50, verbose_name='교수명')),
                ('room', models.CharField(blank=True, max_length=30, verbose_name='강의실')),
                ('building', models.CharField(blank=True, max_length=50, verbose_name='강의실 위치')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '현재 수강과목',
                'verbose_name_plural': '현재 수강과목',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='인증 코드')),
                ('purpose', models.CharField(default='signup', max_length=20, verbose_name='용도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('expires_at', models.DateTimeField(verbose_name='만료 시각')),
                ('is_used', models.BooleanField(default=False, verbose_name='사용 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '이메일 인증',
                'verbose_name_plural': '이메일 인증',
            },
        ),
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('IT/개발', 'IT/개발'), ('디자인', '디자인'), ('마케팅/광고', '마케팅/광고'), ('금융/회계', '금융/회계'), ('교육', '교육'), ('공기업/공공기관', '공기업/공공기관'), ('의료/바이오', '의료/바이오'), ('미디어/콘텐츠', '미디어/콘텐츠'), ('건축/공간', '건축/공간'), ('스포츠/예술', '스포츠/예술'), ('연구/R&D', '연구/R&D'), ('기타', '기타')], max_length=30, verbose_name='관심분야')),
                ('custom_text', models.TextField(blank=True, verbose_name='자유 텍스트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '관심분야',
                'verbose_name_plural': '관심분야',
            },
        ),
    ]
