# Generated by Django 5.2.12 on 2026-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_chat',
            field=models.BooleanField(default=True, verbose_name='AI 채팅 알림'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_contest',
            field=models.BooleanField(default=True, verbose_name='공모전 알림'),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_notice',
            field=models.BooleanField(default=True, verbose_name='공지 알림'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notification_enabled',
            field=models.BooleanField(default=True, verbose_name='전체 알림'),
        ),
    ]
