# Generated by Django 5.2.12 on 2026-04-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_notification_chat_user_notification_contest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_contest',
        ),
        migrations.AddField(
            model_name='user',
            name='notification_information',
            field=models.BooleanField(default=True, verbose_name='정보 알림'),
        ),
    ]
