# Generated by Django 5.2.12 on 2026-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_notification_contest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='graduation_month',
            field=models.IntegerField(blank=True, null=True, verbose_name='졸업 희망 월'),
        ),
    ]
