# Generated by Django 5.2.12 on 2026-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_graduation_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='입학 연도'),
        ),
    ]
