# Generated by Django 5.2.12 on 2026-04-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_admission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='온보딩 완료 여부'),
        ),
    ]
