# Generated by Django 5.2.12 on 2026-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_onboarding_completed'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursehistory',
            constraint=models.UniqueConstraint(fields=('user', 'course_code', 'year', 'semester'), name='unique_course_history_per_term'),
        ),
    ]
