# Generated by Django 5.2.12 on 2026-04-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_coursehistory_unique_course_history_per_term'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='currentcourse',
            constraint=models.UniqueConstraint(fields=('user', 'day_of_week', 'start_time'), name='unique_current_course_per_slot'),
        ),
    ]
