# Generated by Django 5.2.12 on 2026-05-16 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_currentcourse_unique_current_course_per_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('notice', '공지'), ('information', '정보')], max_length=20, verbose_name='북마크 대상 종류')),
                ('object_id', models.IntegerField(verbose_name='대상 객체 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='북마크 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'content_type', '-created_at'], name='accounts_bo_user_id_5ce7cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_bookmark_per_user_target')],
            },
        ),
    ]
