# Generated by Django 5.2.12 on 2026-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehistory',
            name='liberal_subtype',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='교양 4종 분류'),
        ),
    ]
