# Generated by Django 5.2.12 on 2026-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_coursehistory_liberal_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursehistory',
            name='core_area',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='핵심교양 영역'),
        ),
    ]
