# Generated by Django 5.2.12 on 2026-05-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_coursehistory_core_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chapel_count',
            field=models.IntegerField(default=0, verbose_name='채플 누적 이수 회수'),
        ),
    ]
