# Generated by Django 5.2.12 on 2026-05-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_chapel_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password_hash', models.CharField(max_length=128, verbose_name='비밀번호 해시')),
                ('code', models.CharField(max_length=8, verbose_name='인증 코드')),
                ('code_expires_at', models.DateTimeField(verbose_name='코드 만료 시각')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='실패 시도 횟수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신 시각')),
            ],
            options={
                'verbose_name': '가입 임시 보관',
                'verbose_name_plural': '가입 임시 보관',
            },
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='purpose',
            field=models.CharField(default='password_reset', max_length=20, verbose_name='용도'),
        ),
    ]
