# Generated by Django 5.2.12 on 2026-05-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cleanup_unverified_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursehistory',
            name='category',
            field=models.CharField(choices=[('전공필수', '전공필수'), ('전공선택', '전공선택'), ('공통교양', '공통교양'), ('핵심교양', '핵심교양'), ('학문기초교양', '학문기초교양'), ('일반교양', '일반교양'), ('자유선택', '자유선택')], max_length=20, verbose_name='이수구분'),
        ),
    ]
