# Generated by Django 5.2.12 on 2026-05-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_coursehistory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentcourse',
            name='building',
        ),
    ]
