# Generated by Django 5.2.12 on 2026-06-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_currentcourse_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_job',
            field=models.CharField(blank=True, max_length=100, verbose_name='목표 직무'),
        ),
    ]
