# Generated by Django 5.2.12 on 2026-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_target_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentcourse',
            name='offering_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='분반 id (등록 시점 CourseOffering PK)'),
        ),
    ]
