# Generated by Django 5.2.12 on 2026-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('academic', '학사공지'), ('general', '일반공지'), ('event', '행사공지'), ('scholarship', '장학공지'), ('overseas', '해외공지'), ('student_activity', '학생활동공지'), ('career', '진로/취업/창업'), ('contest', '공모전공지'), ('opentalk', '오픈톡')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=500)),
                ('published_at', models.DateTimeField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'notices_notice',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['source', '-published_at'], name='notices_not_source_9f7d4b_idx'), models.Index(fields=['-published_at'], name='notices_not_publish_18f74b_idx')],
                'unique_together': {('source', 'url')},
            },
        ),
    ]
