# Generated by Django 5.2.12 on 2026-05-05 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeAIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(blank=True, choices=[('정보형', '정보형'), ('행동형', '행동형')], default='', max_length=10)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('cards', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('success', '성공'), ('failed', '실패')], default='pending', max_length=20)),
                ('last_stage', models.CharField(blank=True, choices=[('classify', '유형 분류'), ('summarize', '요약'), ('build_cards', '카드 구조화')], default='', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_result', to='notices.notice')),
            ],
            options={
                'db_table': 'notices_ai_result',
                'indexes': [models.Index(fields=['status'], name='notices_ai__status_37bcfe_idx'), models.Index(fields=['-updated_at'], name='notices_ai__updated_7fd83c_idx')],
            },
        ),
    ]
