# Generated by Django 5.2.12 on 2026-05-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_noticeairesult'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='extracted_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notice',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
