# Generated by Django 5.2.12 on 2026-05-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_notice_extracted_content_notice_image_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeairesult',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('processing', '처리중'), ('success', '성공'), ('failed', '실패'), ('empty_content', '본문 없음')], default='pending', max_length=20),
        ),
    ]
