# Generated by Django 5.2.12 on 2026-05-14 07:17
# spec 4.4 — 제목 [부서명] 접두사 분리 추출

import re

from django.db import migrations, models


# 마이그레이션 내부 정규식 (base.py의 _DEPT_PREFIX_RE와 동일 패턴)
_DEPT_PREFIX_RE = re.compile(r'^\s*\[\s*([^\[\]]+?)\s*\]')


def backfill_department(apps, schema_editor):
    """기존 Notice의 title에서 [부서명] 접두사 추출해 department 채우기.

    - 패턴 없는 행은 건드리지 않음 (default '' 그대로)
    - title은 원본 그대로 보존
    """
    Notice = apps.get_model('notices', 'Notice')
    updated = 0
    for notice in Notice.objects.all().only('id', 'title', 'department'):
        m = _DEPT_PREFIX_RE.match(notice.title or '')
        if m:
            dept = m.group(1).strip()
            if notice.department != dept:
                notice.department = dept
                notice.save(update_fields=['department'])
                updated += 1
    print(f'  → backfilled department for {updated} notices')


def clear_department(apps, schema_editor):
    """롤백 시 department 비우기 (필드 삭제는 schema_editor가 자동 처리)."""
    Notice = apps.get_model('notices', 'Notice')
    Notice.objects.update(department='')


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_alter_noticeairesult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(
            backfill_department,
            reverse_code=clear_department,
        ),
    ]
