# Generated by Django 5.2.12 on 2026-05-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_add_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeairesult',
            name='last_stage',
            field=models.CharField(blank=True, choices=[('summarize', '요약'), ('classify', '유형 분류'), ('build_cards', '카드 구조화'), ('extract_tags', '키워드 추출')], default='', max_length=20),
        ),
    ]
