# Generated by Django 5.2.12 on 2026-04-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=50)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('전공필수', '전공필수'), ('전공선택', '전공선택'), ('교양필수', '교양필수'), ('교양선택', '교양선택')], max_length=10)),
                ('credits', models.IntegerField()),
                ('year_open', models.IntegerField()),
                ('semester_open', models.IntegerField()),
                ('professor', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'courses_course',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('pre_registration_start', models.DateField(blank=True, null=True)),
                ('pre_registration_end', models.DateField(blank=True, null=True)),
                ('registration_start', models.DateField(blank=True, null=True)),
                ('registration_end', models.DateField(blank=True, null=True)),
                ('adjustment_start', models.DateField(blank=True, null=True)),
                ('adjustment_end', models.DateField(blank=True, null=True)),
                ('semester_start', models.DateField(blank=True, null=True)),
                ('semester_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'courses_academiccalendar',
                'unique_together': {('year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금')], max_length=2)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('building', models.CharField(blank=True, default='', max_length=50)),
                ('room', models.CharField(blank=True, default='', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course')),
            ],
            options={
                'db_table': 'courses_courseschedule',
            },
        ),
        migrations.CreateModel(
            name='GraduationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('admission_year', models.IntegerField()),
                ('category', models.CharField(choices=[('전공필수', '전공필수'), ('전공선택', '전공선택'), ('교양필수', '교양필수'), ('교양선택', '교양선택')], max_length=10)),
                ('required_credits', models.IntegerField()),
                ('total_required', models.IntegerField()),
            ],
            options={
                'db_table': 'courses_graduationrequirement',
                'unique_together': {('department', 'admission_year', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='courses.course')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='courses.course')),
            ],
            options={
                'db_table': 'courses_courseprerequisite',
                'unique_together': {('course', 'prerequisite')},
            },
        ),
    ]
