# Generated by Django 5.2.12 on 2026-05-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
