# Generated by Django 5.2.12 on 2026-05-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester_open',
            field=models.IntegerField(choices=[(1, '1학기'), (2, '2학기'), (3, '하계 계절학기'), (4, '동계 계절학기')]),
        ),
    ]
