# Generated by Django 5.2.12 on 2026-05-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_semester_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField(choices=[(1, '1학기'), (2, '2학기'), (3, '하계 계절학기'), (4, '동계 계절학기')])),
                ('section_no', models.CharField(max_length=10)),
                ('professor', models.CharField(blank=True, default='', max_length=50)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='courses.course')),
            ],
            options={
                'db_table': 'courses_courseoffering',
                'ordering': ['year', 'semester', 'section_no'],
                'unique_together': {('year', 'semester', 'section_no')},
            },
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.courseoffering'),
        ),
    ]
