# Generated by Django 5.2.12 on 2026-05-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseoffering_courseschedule_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='liberal_subtype',
            field=models.CharField(blank=True, choices=[('공통교양', '공통교양'), ('핵심교양', '핵심교양'), ('학문기초교양', '학문기초교양'), ('일반교양', '일반교양')], max_length=10, null=True),
        ),
    ]
