# Generated by Django 5.2.12 on 2026-05-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_liberal_subtype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduationrequirement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='graduationrequirement',
            name='liberal_subtype',
            field=models.CharField(blank=True, choices=[('공통교양', '공통교양'), ('핵심교양', '핵심교양'), ('학문기초교양', '학문기초교양'), ('일반교양', '일반교양')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='category',
            field=models.CharField(choices=[('전공필수', '전공필수'), ('전공선택', '전공선택'), ('교양필수', '교양필수'), ('교양선택', '교양선택'), ('자유선택', '자유선택')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='graduationrequirement',
            unique_together={('department', 'admission_year', 'category', 'liberal_subtype')},
        ),
    ]
