# Generated by Django 5.2.12 on 2026-05-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_graduationrequirement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduationrequirement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='core_area',
            field=models.CharField(blank=True, choices=[('역사와 철학', '역사와 철학'), ('사회와 공동체', '사회와 공동체'), ('문화와 예술', '문화와 예술'), ('과학기술과 정보', '과학기술과 정보')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='graduationrequirement',
            name='core_area',
            field=models.CharField(blank=True, choices=[('역사와 철학', '역사와 철학'), ('사회와 공동체', '사회와 공동체'), ('문화와 예술', '문화와 예술'), ('과학기술과 정보', '과학기술과 정보')], max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='graduationrequirement',
            unique_together={('department', 'admission_year', 'category', 'liberal_subtype', 'core_area')},
        ),
    ]
