# Generated by Django 5.2.12 on 2026-05-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_expand_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='core_area',
            field=models.CharField(blank=True, choices=[('역사와 철학', '역사와 철학'), ('사회와 공동체', '사회와 공동체'), ('문화와 예술', '문화와 예술'), ('과학기술과 정보', '과학기술과 정보'), ('기독교', '기독교'), ('사고와 표현', '사고와 표현'), ('언어', '언어'), ('진로와 디지털리터러시', '진로와 디지털리터러시')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='core_area',
            field=models.CharField(blank=True, choices=[('역사와 철학', '역사와 철학'), ('사회와 공동체', '사회와 공동체'), ('문화와 예술', '문화와 예술'), ('과학기술과 정보', '과학기술과 정보'), ('기독교', '기독교'), ('사고와 표현', '사고와 표현'), ('언어', '언어'), ('진로와 디지털리터러시', '진로와 디지털리터러시')], max_length=20, null=True),
        ),
    ]
