# Generated by Django 5.2.12 on 2026-06-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_core_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
