# Generated by Django 5.2.12 on 2026-05-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('organizer', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'information_contest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='information_created_dfe630_idx'), models.Index(fields=['end_date'], name='information_end_dat_65249d_idx'), models.Index(fields=['is_active'], name='information_is_acti_51bdb7_idx')],
            },
        ),
    ]
