# Generated by Django 5.2.12 on 2026-05-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contest',
            new_name='Information',
        ),
        migrations.RenameIndex(
            model_name='information',
            new_name='information_created_6042c3_idx',
            old_name='information_created_dfe630_idx',
        ),
        migrations.RenameIndex(
            model_name='information',
            new_name='information_end_dat_9782fc_idx',
            old_name='information_end_dat_65249d_idx',
        ),
        migrations.RenameIndex(
            model_name='information',
            new_name='information_is_acti_01e124_idx',
            old_name='information_is_acti_51bdb7_idx',
        ),
        migrations.AlterModelTable(
            name='information',
            table=None,
        ),
    ]
