# Generated by Django 5.2.12 on 2026-05-13 06:55
# 위비티 중복 저장 이슈 해결 — (source, source_id) unique 도입 + 기존 데이터 백필·dedup

import re

from django.db import migrations, models


_IX_RE = re.compile(r'[?&]ix=(\d+)')


def backfill_source_fields(apps, schema_editor):
    """기존 Information 레코드에 source / source_id를 채우고 중복 dedup.

    - URL이 wevity.com 도메인이면 source='wevity', source_id=ix (URL의 ix 파라미터)
    - 같은 (source, source_id)가 여러 건이면 가장 먼저 생성된 것만 keep, 나머지 삭제
    - source를 알 수 없는 레거시 행은 source/source_id 빈 채로 둘 수 없음
      (이후 UniqueConstraint 충돌 방지) → URL을 source_id로 사용 (truncate to 50)
    """
    Information = apps.get_model('information', 'Information')

    # 1) 백필
    for info in Information.objects.all():
        if info.source and info.source_id:
            continue  # 이미 값 있음 (개발 중 부분 실행 대비)
        if 'wevity.com' in info.url:
            m = _IX_RE.search(info.url)
            if m:
                info.source = 'wevity'
                info.source_id = m.group(1)
            else:
                # ix 파라미터 없는 wevity URL — 비정상이지만 dedup 대비 URL 끝부분 사용
                info.source = 'wevity'
                info.source_id = info.url[-50:]
        else:
            # 알 수 없는 출처 — URL 자체를 식별자로 (50자 제한)
            info.source = 'unknown'
            info.source_id = info.url[-50:]
        info.save(update_fields=['source', 'source_id'])

    # 2) (source, source_id) 기준 dedup — 가장 먼저 생성된 행만 keep
    seen: dict[tuple[str, str], int] = {}
    to_delete: list[int] = []
    for info in Information.objects.order_by('created_at').values(
        'id', 'source', 'source_id'
    ):
        key = (info['source'], info['source_id'])
        if key in seen:
            to_delete.append(info['id'])
        else:
            seen[key] = info['id']

    if to_delete:
        Information.objects.filter(id__in=to_delete).delete()


def noop_reverse(apps, schema_editor):
    """롤백 시 — source/source_id 비우기 (dedup된 데이터는 복구 불가).

    이 마이그레이션은 데이터 dedup이 동반되므로 사실상 비가역적.
    롤백이 필요한 경우 백업에서 복원해야 함.
    """
    Information = apps.get_model('information', 'Information')
    Information.objects.update(source='', source_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_rename_contest_information_and_more'),
    ]

    operations = [
        # 1. 필드 추가
        migrations.AddField(
            model_name='information',
            name='source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='information',
            name='source_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        # 2. URL unique 제거 (위비티는 cidx 다르면 다른 URL이지만 같은 공모전)
        migrations.AlterField(
            model_name='information',
            name='url',
            field=models.URLField(max_length=500),
        ),
        # 3. 데이터 백필 + 중복 제거 (UniqueConstraint 추가 전에)
        migrations.RunPython(
            backfill_source_fields,
            reverse_code=noop_reverse,
        ),
        # 4. 인덱스
        migrations.AddIndex(
            model_name='information',
            index=models.Index(fields=['source', 'source_id'], name='information_source_ec9040_idx'),
        ),
        # 5. (source, source_id) UNIQUE 제약 — 백필 완료 후 적용
        migrations.AddConstraint(
            model_name='information',
            constraint=models.UniqueConstraint(fields=('source', 'source_id'), name='unique_information_source'),
        ),
    ]
