# Generated by Django 5.2.12 on 2026-06-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_add_source_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
